### ISSUE TITLE
Support cross-compilers and multiple gcc

### ISSUE THREAD

**Issue by singalen** [olibre/colorgcc#4]
I had exactly the same issue as this one: http://stackoverflow.com/questions/32209094/colorgcc-and-toolchain-prefix
I believe, this can be done without hard-configuring `gcc` to `arm-none-eabi-gcc`. 

The idea is to take `argv[0]`. 

For example, if `colorgcc` was invoked as `arm-none-eabi-gcc`, find the first `arm-none-eabi-gcc` on `$PATH` other than `colorgcc`, and run it.

**Comment by singalen** [comment]
Hmm, in this version it actually works!

**Comment by olibre** [comment]
Thanks for your feedback.

Therefore I have posted an answer on SO to explain how to proceed:  
http://stackoverflow.com/a/41459773/938111

Please let me know if this answer is fine and if this answer can help other people having same issue as you.

Cheers

**Comment by singalen** [comment]
Upvoted. Thanks for your work!
